spring:
  application:
    name: healthrib
  config:
    import:
    - optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
  profiles:
    active:
    - dev
server:
  port: 8080