spring:
  application:
    name: healthrib
  config:
    import:
    - optional:configserver:https://literary-deana-memphyz-672fb30d.koyeb.app/
  cloud:
    config:
      profile: ${spring.profiles.active}
  profiles:
    active:
    - dev
    - prod
server:
  port: 8080