spring:
  application:
    name: healthrib
  config:
    import:
    - optional:configserver:https://literary-deana-memphyz-672fb30d.koyeb.app/
  cloud:
    config:
      profile: dev
  profiles:
    active:
    - dev
server:
  port: 8080