spring:
  application:
    name: sst
  main:
    allow-circular-references: true
  config:
    import:
    - optional:configserver:https://server-config.koyeb.app/
  cloud:
    config:
      profile: ${spring.profiles.active}
  profiles:
    active:
    - dev
    - prod
server:
  port: 8080
